### ISSUE TITLE
Keep the controls visible at all time (long playlists)

### ISSUE THREAD

**Issue by gabrosz** [gsuitedevs/drive-music-player#12]
Hi, it would be nice to have also the next/prev (:fast_forward:/:rewind:) button as there is in a usual player. :relaxed: 
(Shuffle :twisted_rightwards_arrows: and repeat :repeat:/:repeat_one: buttons are really good and working well, which are also a thankful features!:wink:)

For those who use longer playlist it would be nice and easy to have the player handler buttons fixed on top, the add audio tools fixed on bottom, and the list of the playlist scrolling between...

Thanks! ;-)

**Comment by nicolasgarnier** [comment]
I've added back and forward buttons. I'll have a look at making the controls/buttons fixed positioning (the UI has changed a bit so you snippet won't look good anymore but thanks for it!)

**Comment by serdnab** [comment]
@nicolasgarnier 
what do you think would be better, the track list inside a scrollable container or the controls at fixed position?

**Comment by serdnab** [comment]
@nicolasgarnier 
could you please give me your opinion, I'm interested in implementing this request.

**Comment by grant** [comment]
Sorry @nicolasgarnier wasn't able to reply. You change is certainly an improvement, and so I've merged it.
Thanks for the contribution.
