### ISSUE TITLE
Drive Player website down and not accessible.

### ISSUE THREAD

**Issue by pb1051** [gsuitedevs/drive-music-player#275]
## Expected Behavior

Open with Drive Player, music to play with Drive Player.

## Actual Behavior

Drive Player website down and not accessible.

## Steps to Reproduce the Problem

1.Open with Drive Player, music to play with Drive Player.

## Specifications

- Browser: Opera
- OS: Windows

**Comment by sqrrrl** [comment]
Still an issue? Just checked and site is still running fine AFAICT.

**Comment by pb1051** [comment]
I've moved to Fedora and don't have a Windows machine to test any longer

**Comment by sqrrrl** [comment]
Site appears fine (up and serving, didn't verify app is fully working). Closing since no additional details available.
